openapi: 3.0.0
info:
  title: Device Service API
  description: API for managing electronic devices and promotions
  version: 1.0.0

paths:
  /devices:
    get:
      summary: Retrieve a list of all devices
      description: <b>Scope required:</b> `devices_list`
      responses:
        '200':
          description: A list of all devices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
    post:
      summary: Add a new device
      description: <b>Scope required:</b> `devices_add`
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceInput'
      responses:
        '201':
          description: The newly created device
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'

  /devices/search/{name}:
    get:
      summary: Search a device by name
      description: <b>Scope required:</b> `devices_list`
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
          description: Name of the device to search
      responses:
        '200':
          description: The requested device
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '404':
          description: Device not found

  /devices/{device_id}:
    parameters:
      - in: path
        name: device_id
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1
        description: ID of the device to retrieve or modify
    get:
      summary: Retrieve a device by ID
      description: <b>Scope required:</b> `devices_list`
      responses:
        '200':
          description: The requested device
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '404':
          description: Device not found
    put:
      summary: Update a device
      description: <b>Scope required:</b> `devices_modify`
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceInput'
      responses:
        '200':
          description: The updated device
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '404':
          description: Device not found
    delete:
      summary: Remove a device
      description: <b>Scope required:</b> `devices_delete`
      responses:
        '204':
          description: Device removed
        '404':
          description: Device not found

  /promotions:
    get:
      summary: Get all promotions
      description: <b>Scope required:</b> `promotions_list`
      operationId: getPromotions
      tags:
        - promotions
      responses:
        '200':
          description: List of promotions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Promotion'
        '404':
          description: No promotions found

    post:
      summary: Add new promotion
      description: <b>Scope required:</b> `promotions_add`
      operationId: addPromotion
      tags:
        - promotions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromotionInput'
      responses:
        '201':
          description: The newly created promotion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Promotion'
        '400':
          description: Invalid input
        '409':
          description: Promotion with provided promo_code already exists

  /promotions/{promo_id}:
    parameters:
      - in: path
        name: promo_id
        required: true
        schema:
          type: integer
        description: Numeric ID of the promotion to get or update
    get:
      summary: Get promotion by ID
      description: <b>Scope required:</b> `promotions_list`
      operationId: getPromotionById
      tags:
        - promotions
      responses:
        '200':
          description: The requested promotion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Promotion'
        '404':
          description: Promotion not found

    put:
      summary: Update promotion by ID
      description: <b>Scope required:</b> `promotions_modify`
      operationId: updatePromotionById
      tags:
        - promotions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromotionInput'
      responses:
        '200':
          description: The updated promotion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Promotion'
        '400':
          description: Invalid input
        '404':
          description: Promotion not found

    delete:
      summary: Delete promotion by ID
      description: <b>Scope required:</b> `devices_list`
      operationId: deletePromotionById
      tags:
        - promotions
      responses:
        '204':
          description: Promotion deleted
        '404':
          description: Promotion not found

  /promotions/devices:
    post:
      summary: Add promotion to devices
      description: <b>Scope required:</b> `promotions_modify`
      operationId: addPromotionToDevice
      tags:
        - promotions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddPromotionToDeviceInput'
      responses:
        '200':
          description: The updated list of devices with added promotion
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
        '400':
          description: Invalid input
        '404':
          description: Promotion or device not found

  /sales:
    get:
      summary: "Sales Trends API"
      description: <b>Scope required:</b> `sales_trends_view`
      operationId: getSalesTrend
      tags:
        - sales
      responses:
        '200':
          description: List of sales
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Promotion'
        '404':
          description: No promotions found

components:
  schemas:
    Device:
      type: object
      properties:
        device_id:
          type: integer
          format: int64
        name:
          type: string
        image_uri:
          type: string
        qty:
          type: integer
          format: int32
        description:
          type: string
        price:
          type: number
          format: float
        promo_id:
          type: array
          items:
            type: integer
            format: int64
      required:
        - device_id
        - name
        - qty
        - description
        - price

    DeviceInput:
      type: object
      properties:
        name:
          type: string
        image_uri:
          type: string
        qty:
          type: integer
          format: int32
        description:
          type: string
        price:
          type: number
          format: float

    Promotion:
      type: object
      properties:
        promo_id:
          type: integer
          format: int64
        promo_code:
          type: string
        discount:
          type: number
          format: float
        tier:
          type: array
          items:
            type: string
            enum: [Silver, Bronze, Platinum, None]
        devices:
          type: array
          items:
            type: integer
            format: int64
      required:
        - promo_id
        - promo_code
        - discount


    PromotionInput:
      type: object
      properties:
        promo_code:
          type: string
        discount:
          type: number
          format: float
        tier:
          type: array
          items:
            type: string
            enum: [Silver, Bronze, Platinum, None]

    AddPromotionToDeviceInput:
      type: object
      required:
        - promo_code
        - device_ids
      properties:
        promo_code:
          type: string
          description: The code of the promotion to add
        device_ids:
          type: array
          items:
            type: integer
          description: The IDs of the devices to add the promotion to